{"text": "2021-12-18T10:04:05.405627+0300::ERROR::An error has been caught in function '<module>', process 'MainProcess' (6316), thread 'MainThread' (140135118903104):\nTraceback (most recent call last):\n\n> File \"/home/alexey/TMS/Z63-TMS/students/Aleksey_Darid/hpmework_logg/dec_logg.py\", line 15, in <module>\n    d(3,0)\n    \u2514 <function d at 0x7f73bec02700>\n\n  File \"/home/alexey/TMS/Z63-TMS/students/Aleksey_Darid/hpmework_logg/dec_logg.py\", line 13, in d\n    a/s\n    \u2502 \u2514 0\n    \u2514 3\n\nZeroDivisionError: division by zero\n", "record": {"elapsed": {"repr": "0:00:00.006235", "seconds": 0.006235}, "exception": {"type": "ZeroDivisionError", "value": "division by zero", "traceback": true}, "extra": {}, "file": {"name": "dec_logg.py", "path": "/home/alexey/TMS/Z63-TMS/students/Aleksey_Darid/hpmework_logg/dec_logg.py"}, "function": "<module>", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 15, "message": "An error has been caught in function '<module>', process 'MainProcess' (6316), thread 'MainThread' (140135118903104):", "module": "dec_logg", "name": "__main__", "process": {"id": 6316, "name": "MainProcess"}, "thread": {"id": 140135118903104, "name": "MainThread"}, "time": {"repr": "2021-12-18 10:04:05.405627+03:00", "timestamp": 1639811045.405627}}}
{"text": "2021-12-20T18:44:39.197882+0300::ERROR::An error has been caught in function '<module>', process 'MainProcess' (11803), thread 'MainThread' (140165028226880):\nTraceback (most recent call last):\n\n> File \"/home/alexey/TMS/Z63-TMS/students/Aleksey_Darid/hpmework_logg/dec_logg.py\", line 15, in <module>\n    d(3,0)\n    \u2514 <function d at 0x7f7ab57c3700>\n\n  File \"/home/alexey/TMS/Z63-TMS/students/Aleksey_Darid/hpmework_logg/dec_logg.py\", line 13, in d\n    a/s\n    \u2502 \u2514 0\n    \u2514 3\n\nZeroDivisionError: division by zero\n", "record": {"elapsed": {"repr": "0:00:00.008118", "seconds": 0.008118}, "exception": {"type": "ZeroDivisionError", "value": "division by zero", "traceback": true}, "extra": {}, "file": {"name": "dec_logg.py", "path": "/home/alexey/TMS/Z63-TMS/students/Aleksey_Darid/hpmework_logg/dec_logg.py"}, "function": "<module>", "level": {"icon": "\u274c", "name": "ERROR", "no": 40}, "line": 15, "message": "An error has been caught in function '<module>', process 'MainProcess' (11803), thread 'MainThread' (140165028226880):", "module": "dec_logg", "name": "__main__", "process": {"id": 11803, "name": "MainProcess"}, "thread": {"id": 140165028226880, "name": "MainThread"}, "time": {"repr": "2021-12-20 18:44:39.197882+03:00", "timestamp": 1640015079.197882}}}
